### ISSUE TITLE
Claimable souls spawn on nearest ledge

### ISSUE THREAD

**Issue by sarinjthorn** [Bryan-Legend/metroidvania#63] opened 2023-05-28 22:19 UTC
So the player doesn't have to commit suicide to regain them in lava etc.
![image](https://github.com/Bryan-Legend/metroidvania/assets/102440626/d3f862ab-1429-4c74-8333-3b4ad2569985)

**Comment by Bryan-Legend** [comment] 2023-06-02 20:26
Duplicate of #1

**Closed as completed by Bryan-Legend** 2023-06-02 20:26 UTC
Labels: enhancement
